### ISSUE TITLE
How gitgaurdian/ggcanary make sure the ggcanary users created using this setup are only targetted by hackers?

### ISSUE THREAD

**Issue by anshuca0743** [GitGuardian/ggcanary#32]
In an AWS account where we are creating ggcanary users following the steps mentioned https://github.com/GitGuardian/ggcanary#setup, there might be other IAM users as well and we want the hackers to only access these canary tokens and not the other users' access key, and secret. How can this be ensured using ggcanary? What value this project will add if a real IAM user from the same account gets compromised?

**Comment by gg-mmill** [comment]
Hello, in short, GGCanary will 
1. Create IAM users. 
2. Allow you to programmatically list those users and their credentials (it will not list other IAM users, that you may have created manually for example).
3. You can then use those credentials as "trip-wires", by manually putting them in places where they might be found by a hacker e.g.  If someone tries to use a canary token, you will receive an alert.

> we want the hackers to only access these canary tokens and not the other users' access key, and secret.
I am not sure to understand what you mean by this ? The canary token won't prevent anything really. They are just an alerting system. 

For example, if you store real credentials somewhere, you may also store one canary token, so that if the place containing the real credentials is compromised, the canary token will be used, and cause an alert.

The value is that you will know your real credentials are compromised, and you will be able to take appropriate measures.
